"""
Django settings for News_board_API project.

Generated by 'django-admin startproject' using Django 3.1.
"""
import os  # noqa

from .base_conf import BaseConf


class LocalConf(BaseConf):
    """Local settings for project."""

    DEBUG = True
    SECRET_KEY = "pys^v=+5+!bj4w9%5uxoq2mp@mp9&hybspq_i3fd&jev!z6h_u"

    REDIS_HOST = "redis"
    REDIS_PORT = "6379"
    BROKER_URL = "redis://" + REDIS_HOST + ":" + REDIS_PORT + "/0"
    BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 3600}
    CELERY_RESULT_BACKEND = "redis://" + REDIS_HOST + ":" + REDIS_PORT + "/0"
