# Generated by Django 3.1 on 2020-08-31 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20200831_2118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="creation_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="creation_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
